import type { Metadata } from 'next'
import { Geist, Geist_Mono, Gruppo, Rubik_Mono_One } from 'next/font/google'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const gruppo = Gruppo({
  variable: '--font-gruppo',
  subsets: ['latin'],
  weight: '400',
})

export const rubikMonoOne = Rubik_Mono_One({
  variable: '--font-rubik-mono-one',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${gruppo.className} flex min-h-screen flex-col antialiased`}>
        <Header /> {children} <Footer />
      </body>
    </html>
  )
}
